
export default [
	 {
		"name":"Node.js",
		"icon":"/Images/nodejs-icon.svg"
	 },
	 {
		"name":"React",
		"icon":"/Images/react.png"
	 },
	 {
		"name":"MongoDB",
		"icon":"/Images/mongodb.svg"
	 },
	 {
		"name":"Next.js",
		"icon":"/Images/nextjs.png"
	 },
	 {
		"name":"Bootstrap",
		"icon":"/Images/bootstrap.png"
	 },
	 {
		"name":"TailwindCSS",
		"icon":"/Images/tailwind.png"
	 },
	 {
		"name":"JavaScript",
		"icon":"/Images/javascript.png"
	 },
	 {
		"name":"HTML",
		"icon":"/Images/html.png"
	 }, 
	 {
		"name":"CSS",
		"icon":"/Images/css.png"
	 },
	 {
		"name":"Figma",
		"icon":"/Images/figma.png"
	 }
	]